[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "882c96550d24eccb710ae8b84ff9552707132b96"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "249ea6276ddf84e4c5f0bf95e8ae5a81d1ff9baababc5d54497854c6802639ba"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "b89a19a0bf6148ca2dc42018e1c5eab6be80975d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ee534682667795ea7dda152427facc21b6495f4a2fba8b6c3ca614479ed08872"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "f2c472aa47d6162924d9cbc5cccc7b5a714ba181"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "a6dec4db67f487699dd417de5dd9554579c5946de97e6b0123c6ebe65a385cac"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "43591b9b1f7dae7e3387413e0082af5ce6da5c7d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "4ee4aea71bdd05e4ffa498c2bef904d593610e2c4e4ef721db34c1f81c329c26"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "27ee6b669b3e4724f18191b2182e9d9d2e1c2951"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5693d0136eb8d0b6026258d9942034ee002d13eeeb1597c301b46694bbaaa4e1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "857073db99117f7f6723de7fdad596be7ed26fd3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "01fd832a4cb453330d2807aeb54bf08a6d3c2b6e348fbacd076b06d8169acbf0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "7a9153da72e97de6abd97da53c5cadf21dab7cf2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "22b9a1831b473f25deaade24ecda259b29369555e01d38b6378e4b826cda2660"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d7d0a1c2dba8bd87da5cd85b6b706a92bc031661"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "37e7935c215b6ba14c585ce4dd9534181b8296a3a95f28603c82b11521b3b929"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a3716424fdc8d7a2ff8273cd0537a7a8a09a9ab1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "16d514b6c7a3926c8f4be32b0a1deacb9bac975ba0165e7177937411abc6980d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c9a797e1b403d9aa44f7a17ac3e278e7c369f63b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "44039dd4032959a0c4c368a7db18f19b7d673e20f3aba68c70fe18db4b7e3ac2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cd6840cb1553257ee0e9b0f07b9432331b3262a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b21da6cc4265b624020454977631e3a2da7a70dc0517fb33fb211a7964447d28"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6db453b631d6927c0808ebc684f4dede5c2ed4d8"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "478a538d46392e396b8e877e708a7293ad2d02c00b9a619b6b895df26971bfe0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7b436b599cb1eac72fc0d9359069d9caccbdd117"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e1e142fedb11576ed401f3505baabf67d47aa1d1fa92fb8c79dfecace068c6a9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18b2665d2cc18ba7e984b51993a1b56b6eb4e183"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "95fd92cd0dec92f73eba0f655896056acdead7ef7f921d287c2750d4d7561c66"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7ea04f4325cc906f622ecba72fd0d0261e318fae"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "07506f5e40e137c21b290c22c103ef7cb466011b6ea57c5a7b542839c9b5c9dd"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "94041268338f15c237fcd44580a01508c672487c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "230550555f6046175ebcbe44b3375c0622d7871b6859fd34e6453dd2da738416"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "45ccb6ff1b4de7386c1dec77d8bea5989fa2fa51"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "051571f0dc62b15e2a3bdf00c2bb1a5253b6fed7c048b279a984667a7f211b24"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "177941d3d5c743c05d2a4f701db8cbe947721bd4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "da5719e3d81d6b211480a01f3efc17255e2732eb10bd64e0aa13f406486fea7d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43a24ae4ef61629cf7908a9ce913006a7490b31d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d1ce68d20b5e0b2e6bbf43970939c974b40190bb02362f45bf9a1c6076528e22"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "84bbeee356743a3ad84a141b4329874f20ec4948"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "58bffe33f687928cbebdf47e1dd5f598e764da8bcb6b52b13fe8fee30a451d6d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "2874300c328839f3c012979771ac7912f9fabf42"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5ef02bdd2e3dc29566534e6325d362d90ac18494c567fd90fb57606ba5b08533"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "109a951f86c5ba2ce17f8a315f3a34230a5c588b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2d675b305a106c7be05f8377f7627d1549e5e685c462fa3cacbd1bfc815a0410"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "f8210b8547143454f2f744c8ae58bd061364e4f1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "12e82739a2b57a4ffc23cbb198f94fa0986d8a69d3ad49913a153e378082d489"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "af2877713a54c63ffac3ba46a46158cca9b472cd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "0315f6b13b17c6bbce129f1028f621aa17fa7836ea816069fd23aa392b8ecff5"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "718a24fa5116feebec834bc72b2673848a70025e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2d8bd285ecd5a65f0fe87b66522734ad0747815547f737b72f0d10a84276b0a1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "d40971a279c5245ba28883f6730f27ed29d73a86"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d95378d49f069a9c5470fd710fbc760101c04414f4fef6671d43bb144fd5ca6a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "06e243dfe61388d7d5950ebf1b49cd60b7e48991"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ac9d79d012a2dbd30c237a14924db9826c19cb46984765f665184cd81d80f276"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "488201da8a070e317c0c41573469e822ea2fb209"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2ae0ee7a35b314654dbb3a3192e1586528e17ca0deb63e7b6b9e0aca06712e00"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "6d0e853cde77c7051779298935874df118b005f7"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "857ea3c3d2013f80cd24e6c1904b6351fa01153a5397a0ebea2c1f28489be873"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "16e79e64906d0c40b2987384ec9a20372c2efc89"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "4b07d564215c6d84689e19443d01ce76467e02672095a424af36794fd94106e0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "a0de39bc4b0d830aa59c668fc0321b194357afe6"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "ec3533e844a3f717a8ddc9687260e7a49957d96aa2e46333b8ec3c225e7bcfc6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "4169982d41e6238f5a04b4f1c7e01430631f2cfe"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5068393d0b5ef7fe2a9e2a060d5821040be0c15562ab34a582960dc7871979ae"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1f4b1d30acdd19ed21dd4e6b695be329a4763089"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9e7f49d5378cb0f14196c4edf98c212caa79b8d6390462483cd6ba0c2bf38c3e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "abb123f3a833447a3365c356cc37bf5671f08218"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "0ccd5b51b36af243876b07b0a290bb388603b67962eac748b8e134e0724829ae"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e681091a6d39132c3da6d5dda1e81cfd58a108dc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "17ffd573c680210d30996f6c1f1c13a25dc14f618b670e2b27cdde0f65586757"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "32c196f3990fcda87f3a8d9574e01e2ec2feb1f3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5c1439d4c373d724e2323a484267f2799bc3275c871c6f08859599b1440c751f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "df114ef7a4113c1fc7c326def2f8bb0000b4e9b4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "43be429051c089da97d3f8d61974b0321302d60972d8ed643cc5359cc485076d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "a4e4d32af4926ea11a962c1c4be935e95325a52c"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "1eef8a8888501d312761a3fe99a4c86f386fb95befe9872f5afcc84d0663e4c4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1c68d5d951017361edb2d58deedd58624261cb17"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "122cff7a515168009866c8989a67042ebea52d624189e73a2140495d94a86edb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "79801f5c4c2f2974fb93bf274e1419f0ddef0775"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "6b5eae62c2ce01b387c850ce4b8e72d5cad1cb963688cd68d6669c1cc62644d6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "734a8d414808d5ac359a4aee3555aff1d309435d"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "fc66543707b3b41ea6b3912d0a6b6e7f5212a4614a5eef2a7e6874c5dd1b9ad6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "74388b9c95b667de0f1722b9233c541557ee594c"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "004168e07c25633ee26aeaea7520662e6d137c8a196d6d260d8c5f814f2a6ccf"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e705619959c9c8a1301348269ec8c1ad4e114ed8"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "e7be650261162e721e609d99413c98a943539b88a14f0f80f66d9f037bf4f343"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+2/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
