[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "df2c8a53b78b689bd045781ce15fd11b989a37d6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "dcf3871f7bfd19b331371c58db6aad90727987639a07622f8d5cb66f7870a49c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "dffa12539ad688a8af7887b395f033394efe441a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1826725cf3b2ed5a5a988be75149a2cf8a8ff8ba81723c4b18a11a2e0cdbd6e2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "983594fdb7394b984dd1a7e6b1a9c0548488871d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "57a24f5f8b64c2c013866135a974d50d0e5123be6f72a29026811bcc1810680f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "b27aa6a937aa27cc9d309f90d8df33a3ad23018f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "6d317d3769bd6966a496208217e8e69bff64b3449b04967421de61c4028dcb41"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "8d5411922f48ba63653abe2247f3108e4988e907"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f1b1b93dac7f6c3a4aff362aaca913ce3ff08b506e62ecde08c2b431ebccd943"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "172e8a2463cbe7a47cc5168d143c98b648ea337a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "7895aa07b8ccda281c48891fb32b03cef8efcae57a1672b55111e33e1e8aa147"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f7d01e8cce3593a2d3257dc4107f519a966e7297"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "957c8db20c034f56118bef208e893e2240c0d5d967f9ee10b551cec51d67bfc0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b1476b4e32f3dc16692d070d0424419f40ef97c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "25134787964be42c9042f920935c19b54a0703cf5b017983492f7a8fed1e5093"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2228d90afdd20b638f605e36587573baa9c06875"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "952180492c22d41d9a0d5e7ff0f3f46a74bacfb70bc24209506400e1ebec86ee"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0ca696444140d385dcdac9908340ff9b1aa00f52"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c36df1ca68017f720ffa038aa95ac60c652d31b57fc5110f39c29a68eb92cc23"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "dc0a22313bcb6596243727540453c1022e529e59"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "aaf6fa8b4819bb92046529fe8bfa158060db8e23c18a5ccd6d3082be77b858e2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "535bbbeaee52377665f845a3b21123db623f6896"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "4029fbf8e38253a4814ce769b4e6397b21db06174bf194bca6fdedda1ee9c9da"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "bd2e45ac547bdd59c680de7f3298e4c79acb3015"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f0f4010ebf25fde7b0004201b425ac38fddfb01536616726de4a38229cdd7a7c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "03adc4730afb72c861332e80cbfe5d1dbcbaf8b9"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "498b89c765398ab56cfc7cbfcfa4c3bb55b14c318cc6a6daa25fa17751ba39d1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "90030ab58a54d145e3859f1edd8235805842761c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "41f3af709dd86ddb024e8144fc2c87dca366b25672085de57542c9186e89a0e8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "f0b2e6418811419a8ed0b39223a4be76d6b1d4a0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "0776b01c528d4c72f5db4f292044cd6e401340831a0307526bb2f564163a87a8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "ceb9bef0c51db565c85ac6a2f53a26c0b35c7b0a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "20bfaca3ff82986b5835ae993543f717d5f26d80c44308ab82e7a451194e5c36"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "545a4e96cfd9805bad14d24af4545895af7a1941"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "44ca7b5830f8ec1902c4b0aec80f808e04e9caa33e8b09fc65622da3648cbf04"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "d49b0eec4df1deb85a88609a5e708691328328b4"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "963cdc570f3f06f6a112cd05e1ca96daa4e330378a705f30843be773559aa3b1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "3248e823afaf771b230b3da3657f7158b1b42f8e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "a62ef6ea62eb0c500f8d1186211ee30448f24c29bee4f1d21912b568c1c1221d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "c5d6e656a7548fd908ddb67da43120e62906f4f9"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "cf1195660da9271602f747a96109d1dc23cb304d1e3f451ad3f4b6fbae039630"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "cf69bd3a7a1bf17a8701a8236da26f8f92dfdafb"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "534b42707d416008f8992a55d6c808013fe7a2a62203e9e3775d489cca7ef014"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c210538ad6a31690b94a834d195aee1b7c812987"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "75a039d864d9642713bcb689d76c49becc6149d564a68d8e31ca9dd4301f024e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "59b26abc6101d48c80b92e9dd3fbf5b98080e6e6"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "ffc53bccb9698a5aa7e918b37af9db476ac5f24638954a9ed02c16b8a6c91b2e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e5d6823e1b6994704723db1d277be4aaaf211011"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c014ccd41f549482c8afa9ca196911c8dffefd287aa3f820849f1f3724550b24"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1947582c4c4a8345b2d1c9cb2678a0bddae8954b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f928751fbabf4f2cd84f5e124fbdc423868db4050a2eae8caf54937cf285b666"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "b69bd31eee9ae9df45bca608ccbe4bf8816ff841"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "a00602180f91d62dfe9080cb908a8f002baf7a1c4033a0818b70d72baace768d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "4a0c30496cccf74de3cc66fec14f51384d3cc5a5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "cdf1a670c323334fb27f81b96567a50a57e4760cf27e6091c4303f8ae0795fe8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "9efeb20ee3ca78b92a4f5e02087a1832ef6035ba"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "3eb7a31074a8a1e19b55637d5d869a36046d3619d6e887474ec68c38d92ab926"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "2882e62aff816b41fbbaa2eedabf46a867d3787a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "58b9cfe7108c61d7d2994e8b815af1402536655d846a7a2aea0f1dfa0aff0f7c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "99632f8ebe5bb02dfadb6a0bd2ae8fbf1e5a3622"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "fdfe8d0c33e3011e9c0356286b8986afa3473d676d676bde59427390ea81489e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d12ec81cd354f22572a79373bf1acddb52884c65"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "5d2ec39ddc87138800ff7f25c9476e708bcb2daa464e6f6200d25f1d298e0b2f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "848ff12b8a4a785b76dea7357e4cb592232b2301"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "f280efb2b989254e37acdbd8f53fe940c809dbf0f79f61550610b9301bdde04e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "dce24aa591c25143e4174c90a13950a1720af71f"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "97ec48d2a02c88aa445d0fe6313e9cd7d7d69879fcf0a1b471c2adc8feb6a94d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "0b0557ef98a416288b325c0e4b10f1c39ab2dcf2"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "71821560cca759b1e1282d9d22a49ea0b9642a0f95742f732f6920adab2ee7c7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e3422549e74b8579bb24ea945fc1507bbc52fc72"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "d03293b2d0fb76b3f09b8148423b3394e6e37ae657c9d6eaf7e17e2eb1ac809d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.15.2+0/PETSc.v3.15.2.x86_64-w64-mingw32-libgfortran5.tar.gz"
