[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "60aabbbbf829881043e75f84073f2dc7638ed11f"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "608d58964c646f44deac1f967569ee0f9f8dae10266452efb9631666501d39fa"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "fdf7aabdb413b0b2db4ca9f14ddd1bf9788a2bc2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "7cc5ab43a1dadcba2844d2b63c014b4a69144de26921ec62d25ec51a4e431892"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "3a6c9521ae8fe0846e8aa1196270836f6c8efb5f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "cd34a83da62b93727be538779ab432090f30b24b4db3ef6c52b459cfb1bc251f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "9a7ba1cc303ab2640af243a15cf68910c383f46f"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5861b7f90890aca01efd792c0e49abebd8b3e54ce40355eb8cf9f1691f228cb6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "6ced7777797ce0ee30796102840739cba5e52c05"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e3c7dddd42511c057787cdaf41e736e044c3b1aa6fecd7144f1fb598bd00966e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "d571f90c526567477ba7ccee3c963345cf0141a5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d6a1b85e75e1385462dc6faca82f74d71af4d20ec297b775019c7ec3e5f6f37f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "a858b02f84239056d086766815e0bff5f22a96e2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "be880826e01235afaf3fc2b8d8a7a8e79d1eda5f44e2272d45f0f348aa6af4c4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "bb80781523ee20b354b8ee9b039ab8268b219477"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8cd31232ff204549db43725f93b58de9c2f3fc77da2233db7f73cedd38746231"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4f086d7d7ebb9dd958dee7f967798864470c7cca"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "61138b042fe9fe21525fdc5a813f302f459c0cc69fc80dd3940fbf00dc1a6b71"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4989917652838781d7b05c3de735e2182bd0b388"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b11f30e4ffd2853b5acc63222819ff941a2ca533cb5498b2c882914d89f28dca"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1c3553bfdf0cb3c76d7ddd0222ca31d944fe598f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1b6d2f6d42962edc961fe2ccbb6af0eb466a5b68dd6dbbb2f4d1b880082ceebf"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d82362e93d9e2ee1dd23a21ee4b3d4d1ca30993a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "510d303f9d20359020bc0d7c0a9b198d33381e89883e96fe1be33060047bc496"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "51b7841e568bf4dc0317ad3a359d7bfdaa7b69b2"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "dd02a18f275bbaf231af2340074b10874465deb40852540f9d39df5e76802924"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8a5aabfc565fd202a77e023d8efe44fad996a31d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "bcfbd6ee7780fb1bd0657fa9468abf42b076b2007160a4bcf20b56a8055e8c70"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "aefc38426484ed51484b5ecea3f417cef32ff783"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e677d0498e09fb4aae59afdbfbd75d3728ba6891d992655b9da2d932cd6f9966"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "34c9ea7f268f9ae148c3fd864cea09d11b1e9b12"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2972822ba4f585b7a18fd79adf098bba9f612ecf668d3b71a7f0b122abc83830"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3dd998a3f833799986bd0afa1de0b9b01dc9e1da"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "887e553411df0cedf863146e1dc5ef3248536de541fb7b7babcb939f7b78e026"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "2e6f847944302857476c0eeadd90081093c58a1b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "eb3f9c948d044380735b4a3d9bd3486bfef96468c0939f8056665ea90b1052d8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31df1935b857aa93591c28c48e619a15da562776"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8628c6b34985004b789eba847db84b8fb45124341c52b2d0393716ea2c0b87da"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "abe7e374f1803167411bed203be0247f1582976a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c964d3042e9714891d4d70af5c96c3efa2d9f477b19e3adb3efe360a7ee7ca68"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "2250ec558755898287a341d15f6fa282d5c9513b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "72ce2600c6518227d80a526ccc2e8507a5ef840981f9f1a7ed0ebfd38517c1da"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "747d6ad3b041d3d653cdb0d0877af0302e1fad68"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "70c27a1a223f59fb19d62a60026152fbe35d78e363d72dd17f7e156b45ba31e8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "5433041f57d714912580aa64064794a78b458581"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "98f09fd04419d7229255e63ff1dc1a5aec63d568f634054c96bb27ef46afdbf1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "5c2b66e948de90ea578fcd703263992469a731a4"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f3d5ced49f95399892ab3f28dbcd7ad480e98e8a44c3a6ab4cff419600783cc8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "70c753c7f56035eb17bc646641cd25c519cb3250"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5a290a666a72ac1138cf1b7c28ab0ea93036587dfaef5a280a3693a3c539cafc"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "75de03d486e5d890c11ca719beee7dcfe4f535ec"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8e5b1e1b54bb668cce1c23f22216ead17b3b90ce15076c9e5f036098d6ee364b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "98693d2bf12dd14a31b5da6779b732cf9004e75f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f46eac1204cc7dc6959f1529edbe0fd1f98709f6fd276741bb9fec10daf0fbb0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "e617a3ac29ef4e51723d24a0f6b29c6b058494c7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1323df4c0d21c3d0b84f2960eb47fbda71156ec108caad7a13d989a18341d312"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "1d898a8d04f1c69737ff2ef99a62fdf89451fa30"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "47fccabae8b3d3bf184f65f7b73fc092f7c61d718c90182985ee413593605319"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d786b2df6a92ccb1e3f0f3d262ecdae355da3557"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "89bd47bf34e1c441c1d0611cf78b2cadacda58e08a4af91e3f21c60d663560dd"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "2d9beea2b445f9ff8d2cbc555eefc49001d4f50e"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "2049ab7e91ab470ef4ce366df2cee48266e65a2da97c6388a0b4019c60d189d8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "ecc8db982742144d007b5d049d9917dcb7ca1437"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1ec3164fe73a01bc61cafada109265d339bdbf70af47d982d352a8af9f48ec34"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "daffe5f206d7757754c5f697e29e7b78fdc8198f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "38ec774534009a234a2b3855cc14fd42c0fd9a9e1c1be5b151891a12d587a90c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "17470af813cfeb60c293fbf7f677c493546e4a2a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e99ddaa8e7e3ac7f0621d8d43d20a85c24e0e93b2303287dbb28f3c50f234cdb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d36bd6f7993a58cc1fbf98e0691609873d5193e4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "6bd2647829d8d4a9713afb42e1d3c940656cfa02cba4025e4b9425a279d310a9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "09bf64cdd2dd8965ec0080e0f750cce9ba8907d1"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "aa64a75acb9d139b8633628a68a54f0c57c10df51116c1ddedaf6ca8908d4931"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8b85daccf6713fc074d05ac9dfe0dcfb8a82260a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "15daf907caf42fe6a1939c525da4086e23e0dd411f072b9204da523755217312"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "a31f36897c5a9b2892c5b8858b9b3abca4b965aa"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "c805ba50df9be1439978152dd2c95aa715083447df3476d1a2091ab548ddac49"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d52b9c714906446cbd5c026281f8e0ea08340b12"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "b7426b9350157a997037febab6b14c9adf6a47780af7135594fa65fe64e4ef23"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c5ab9934a37c4c5adfec9b23e189798ccee7e00e"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "c81604b50f73195ccd5cc936612266c989019f44dfe184605c636c0be64d4bdd"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "944c22375c22a16bc2b230d0a7cd8b8ad25465a9"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "b573b349519e3ef89638f992608f5a09397c76274e69846bfa099c61cb9fdba4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "0a807f8bedf214d974501a25eb5e9dfabb852127"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "0a0c6d91ea6cbb20e1068887cf6a242c37353fc0c59ed16bb7cdf364a9a1fc1d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "57178d453dc3fe6e299c9ea033424c822dc069dc"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "95024c4e4d3a9a2ca2d6d673c67be81c16655e4d73bd192c6e227edcce575ed8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+0/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
