[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "ebf8fad46c6cfa21bf3ccbb722ce375aab80ec2e"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "e7b177c306e1e4a4a7617ec9457d8d3b67e98a51e248f4a895153803970465c2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "2bb44ace1fa978c0b5e9d430dbb39901a6a04e69"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "dd1996fe7f33209d33794b36cb5332a0f03fd9d4c5ee2b033b0e6313c36a4aa9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "5b3a250e9fbbcc2b61c9e96c61a0f1827f1cd2f6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1778b75c669f9b93498cd751456a831465b11a4c9750814d652f1c896e9b8382"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "d280dbef9edf665aaa71aacbfe8ab99cd463ed4c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2bb2ae3a546b809d044d874033791be8cc5d13507ab517ea478c76553e2fe54f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "31876d8311a9641933d61ef64a24e64e1418f6a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "49f38671668bdd30048dbbf70e9e491fd9b4de0653cfa5fb2213d1ab5b703df3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "61d1b7d679db29d1efd7cb9150ddf6985552d928"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9d165a448b930921a89d58a1499d7c653c866b22b2b2b17adc5e424316f86407"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "a4aff59ba1b2beaf8a8fe51ef3f7917562ebed73"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5d639319439b222f1f4a7e89668fa8ec94e8274a2c6491c8743f93ff97aad2e7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d8e2dc3dacfbdf7639782f9b13c2f1d770682315"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "51d0a0da315ae0cd0a19bc3d62acc12812453804e68b0393ecc61d22d83b3e06"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3077c882d251d7835dcec303cac2c5536dbde230"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "6f2f6a0a11f7b1e998ab5def9eca805996745f2405b0117a793aed7d5909999b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20c4fe154a4b3608e77abb3b6b1e6a219d3ad94c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b801d7569c87d385b6ad28db9020daa0300e297ff9631ae931ee1a478e4ae36f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "821e3e33cd93a87f410cec383f80c2985d99f91d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "61574c0a463c53455e0b64edcae9af671c6462dd515290b69f976356f9b5dce6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0e8e16dfd754fe4b821c39f047859f759eb70da2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "38c77b24e7ee2bd739a9a84d6fba21499b1b663e21c10eb1f56db90e804d1ee4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b3a8a09194de3649086cf6019699c86d03eb11d1"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "7e691972363283ac6b9f0debec443ea4995437259d9c65aa8f311c168ccdbc0a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "afc6b6bdec6e6ac42b0355acfe23cd94d70c2b54"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "594704a1135d7edd6e01268e72237a43bf8d76c86eb9788102e456f7218a3af4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "25c24398b3d01623074f7d5817921358bf24c65a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b6be35c0b88b1ded023a8cf397df2c20e918f8bd4fc58cda2cc5aa11298a476b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a8f47d572573afd893854a2cb7460c1055d70b74"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1e36fadb895efdc643a43584476c59d4774fecbe26f08d05c8d780397bd0d50a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "43ee2027d77bc11f1240b45874658a5ab375eb65"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1e6f77260769ffdf239ef8f017814e89d2736588f1e2647ccc1a3f7c1f077397"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b5c8534428f04784449795d861f936cd57c496c9"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "febd18286020711a2f7d066a142861666f727c48cbc36e8e2c64cf71d2d137f1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7a5f030c61faaffc256e015ab04042590ed9b239"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "793f1c43caf129f7cd7a06da1089fc2e5136bf9bff32a24d8737b14520e39be1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "0d30c59ff847957b40594676ee68f30308b9b4ac"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "86ee503d4c39be2ecc6e18c33064a856b855025af5b5d0afc7ef6f2f2935619f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "64a498646a81dcdbb9081175a72d1e9e063df243"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2a5a945b8a0f178da25f46cf1ad8aa7a9e5d1fe4246a5a864e0a388bea1d0b31"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "f40746d6b3cbd94e56f0085c339b31627a975ab4"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "10915dfe140c9a009818999f7315e33e82da450d85c5713521396bbb68bae35c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "f60e777904a69eb4393b2dd51ab63fac9a197100"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "691c3bab0710b74d6498e9b915f437789865a6f46c4bf4f77120cbd0a27c1ad6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "d0a05d313edd3f9910756b6dae8dade80f721e9e"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f417ac76b81265f068b8bbf09eca297b45c517d31a3f72c22908cccf08258420"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "d5fe11865fe7446b67e74a4b8bee9bacc8ba2f34"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "65ed05d0d8e94f342afa66128ba50e9f163b7f04682461f736ff8ac8ae747f0c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "104f0bc1f3ec73b5e4a5a6d4abd8f2793d35e457"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "71fb0d5c007e36369de21266255036ea72c0c50125f75e8d2aacb680d8557866"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "a8f6dda920c22a5939f4f237c9d6a0c0ba01d421"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9cddb84b38d69edd7ba13af23fbd6eca93ac9ca710651f1d72cb28c2c5feed2d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "0f6ecc5f92cb8bb64c0a925ac719f13f045aa9db"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "adf830fff9d38cf2db0c038e4ea77754c8c2912ea6dbf010ef15f0e64af2bb4f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "997bc57c66464b1c39dfb7fd2e37e963ea7b7452"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "8fe2fb6832f1b1f58f83fa37b27fa6bcd298da11d26d0c5f8029cf5caed44682"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7e9716192e32685e8f2d292e4e3d324e7a5e5238"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "b810ff9a25b472d2592b7cd57f713e58116ccfcef3de769b1288373cefeadf77"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "bbc77cbb235cb535ef7dc8070bd75389d2372755"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "aafdf216fdab162f7c521f01dc6d64a3e21b9b933d07bcecf54a54e96c9a36ba"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "f169e5180b9ce0b5474f671f79c3b9d49ca53318"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "3126bc4747be046a56833bca55d0795bc1cdc5055d80a1233c6aa1430d31ca7b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "50074e62bdd5e43e653068888c3583a08e808685"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "fd362935818938cd6e1f89b4eac51c5bb89d46910b02f4a285b298526a740dde"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "5300957ac90466751dff01f70a8f543d41ae1598"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "4179ce627f0b6b8575d05803d264f09f514d20104fd008721c08f3e27b05b312"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "75ad9a7acbdd7fa2e6c4f9da915e8b044e3d0928"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "6650c0a06e6b9f7e33ef66c6d3b3d1849805e04148400e02d0c0f5184b6abdb9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "310dfcab6a868bd0f05e521617176d7210874769"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "13f3cc509207b2c946bdbca9eae8d581bae4ed3dad7a4c123bb599b203346fda"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "b8f28877262a942c9fe83f60c81a05282c32f9b4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5b69771189d43f89c076af2009be73f5a5fa2496613a866e182de834b8244ed8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8243d55e95a74809db309cc5247244a941e4a444"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "54e12f4cdd82f5a852df911728d372b694fb1a8913e1b836884fac08e8b01214"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "19a2a9a744e0994ffa128f4f359275e46e5dfc40"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "7ced8d74648d05735183098e06a72e6aa839ea65aa25e2cc97d0cf1585a5c89e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "020e25a04e4305bc1c8501d308e06d2ca6a8b802"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "94b94fdf504d0e4cf190484d3d3ad7fe4867d8857f12dcaf28cfee41d0201fcb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "659c75241abe11845efa0bf5cce7ea8eadeca1bb"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "62c7c76e2a902f9b1fb10f0c79d11e65e454ad1349451ee2da0952fb9c1c4af3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "108c27cd35ec161284b8fc76788206df63f83e58"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "7f0dc35b0a5efb368c6dbea89f81d1bab2fcb3d911e9fa032e9c4841ef05bdf1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c7ff8d6ffc4e6a7fa633fa8cf1aa280a62aa15b5"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "06e7dbd7c06b39118cd3caea02e4a867a0d98588e0e8b84c3d6edfbcc3f33780"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+5/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
