[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "c939d0927f98c357c05126c4893af03bfaecd3a2"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "7b05bb94faf08e90df8232b84c26ab66c266d8219e084880384be9bb4b9c46dc"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "dbc0739fcb560d4d211cc3c8c811b5f3f521a38b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "3f774601ab92fd0209cab1c8a284925d30affba773491e37454fb803314fc1f7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "a68fd6931c0238dc6167af78b4f9fbb31c0487d6"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ec266a76a3fd1574f483170e603220e379d5bbcc2218745f7a8b65b4537fa3e7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "0277e47a6e5bba5b347c8abe4d0e6f520313dc64"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "42f874e7bad482a39f7d29b088c5f9f33f55b7baf509e892e1e7b43e7ff897de"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "bcaf10a8ccefbe7726a2f7667ae9e7908132b82b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9d1c09d830bf84a2438920a67dd2ab5058aa2d6f4d0615d4d66a229f4b42966c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "b851a5ff67c77d785fae05ea0631c584bcf3738f"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f8228ab9954b55e4a6b2f8055e91032d3db3bbc05f15f1213a9665e0bb71ff65"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "9ab14ef74eb980a3cd71f9c32a38b432e30d7217"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8b090e23e46a7ba14c284e58a63886b83f883ee388ada3449c8e0146a299ed60"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "0f3bf4923792eaf0151d9b2a949a9cc13489fb2f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ea728d8421db2144111b29dab50f114764280249b15374f607b5b604b0f3b74c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b20458a23ffcf7a2d15c493309188a33e046cc7f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "74fbf26328d809ab5530110fa1676d139a1905edba04a310829dc034103c9455"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "59707e68e37f9752cce07bf07bbf450393874a31"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e3e071c7eaee829f898ba6aa84f00083b343b4a57366fd37e2349d8580f488aa"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "888254faab3bb65e9c2d48d28ae0b2a8230d9c5b"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e836b29014bfb19909d6aa9d17b2ce0572e6ab3391bdf0010504bafab19c8609"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8d5fdee29b238366f6be29b26bfeaff7887631df"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "6b135cadb395a700fa5c550aedd1fe07ceb18851fff3fba9c499aebd8b7832e8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c4595636c1ab6911a74d2cb9f54b58983f599a5e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d6a769aea8c0b7aab508393f5760b40e1c6736963339c3a141fe06f2ee0ee6df"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e5175cc5a53dbdef46751fff6c6f1398cc16c7be"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "622bd0a02c2d07d2b5774a15ff074c97bd0e1333a3da2c16325b60bd3cd43644"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "02ef0ba904594c45aae5912066df3a807afc067c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f5afcba6e257c075a75ae97118ae7ab03380ec5d9d2dbeb9575757b63a614576"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "569dfcc3c2afca49afcc0c2c3f87258965b8598b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "05c8d2101f9801cbe6b4b37ec6f6b164d04ea706a725de480bab100f2b1f9855"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5bca0f4bd18c633ad477a88301600f61cab76ef4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e21e833753e76b011fd5e19e6381d9a8fe58b68ecb7d09f08b95f2588c21dd30"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c318a530d0ae00ed1c8da396d553e3558a3117c0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "df77265eed41e4c79c995147de78c5295b3225995140e0e950360482defd0bb9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "31313214a831c7d3f46ed886e64e1eed66f735ec"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c9436e8c79eb6209e3fe78d0de327e06a38adadb7d18dea73459f0b0feb31466"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "c2b9b9ab9b856cbc41a863f086d78b6d3b5053de"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "53912ab5843d05c7df85e1140dabe9cb99845e25868294a49400c2a93bfcad7c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "23bda149a62fae0a8065c84934f8136b3b9f3a25"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "2ae1285928c8c60b3d4e1b04852654ac97984efbbabf7cf6b955621ccc81cefe"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "1bffca7a567b91bff12b5a0da70efba3558e3dd8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b1247042fa24d5cf4a77bbc0dd0f9f46f6c19761f8755fa58b0abc2e30d9b115"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "59b58033f668f7337b7e1523145c2d520719963d"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f815aeaf53f7999fe2e6a340dbc8b0ae86ae002179dd9ef6f053b1c509e6f6a9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "04d940c959f98479fdc2c0b0932a4de70ecd115a"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1ea0aea277359cf807e2128086de41cb64b7d973591617e5b59cdd3efc437e53"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "ff14b7bd6c08069d0cba93c680020dda3e7bdd98"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8ec837871858556e0ca65dbd086089f0f07d05085df0d33d4e93ff13a8d87078"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "f46b4a5421eb5115c6184b3174f5cfae6ed7f9e1"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8a462d2f66eac701a7a468325e46bd27f470d18e41d936433fda1b5ef2d508ae"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "713ea23ff5f948fbf58d4d18d5aad53d9433faa2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "488f570ae7a8469c1fc945b9039baa8db76b714199634d4aa6cc31b60cfb0f00"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "3035b13ae762b0dd796572c11c19494b1fe92786"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ada570e0cac87668977ea0b52b83abf7f8cca545ce141505ead136b27f87b6b3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "40fa3c8f48371dc824ce93b4b63f56ebafcece2b"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "a8f337e09fb98547ef2a18e51a85922c222032f1bd8af2c024326ea0b1c1a7d7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "f0bb88f81d02edd6039f45cd04532874b54ea5d8"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "0ffd0c0b101555d06249bc01b4937b1c7dae17370e615e79b01c4ff9679a65a1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "ca8ce7f67f5d841e0f2c52a74bccf0e80bbc5d5f"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "4274ca978a32e0f08d3c2e0771d4e6e3a87f7409316fdc381eb34a4243741029"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7ff22cd94114e9a2e85c3c5687631b1271c9b46a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "955833bbb38e028a9fbc960e4131ebdc10fbe597c42317f5777694d1da522c08"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "f6703fa1f0fb9337fb43e88caf6daf32ebc06f03"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ff298ff8925cf8ed8d469ea353500a886943e0fa52e66eacef940052e5495922"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "4299714aa169e569ec82e38a6aa3705da984359b"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "948ac2851df137f75ce6cf4819fe75596c13157501581a250f529468d1e27f88"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "fed5746246ba6e8f4b31261bade4196f52771f10"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e2699c6ef2d54030bb113b3a5d6cc8bf7cb29533032a6f3d22db427a31eff30a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "fb2805b1a9bf5cc35420102876417c463cac87d2"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9f8bfebd7309aa4fa6c66585e346e09a2162175d06a3d4c723ba07e033782e88"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "bcb8cc9c940b81a911353cc5ecaafc56f857469e"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d920e4950fe1fc23f09e8805e4b93047b72d28d22e8cf779989613f7a635f480"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d82527ac089b33e2c899d6539dda584fc9cd073f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "1671a2e9700803619853874ea3e7c36a56491f0d8a585be3f1675c17ddd28d5e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8db8ddeee9cf59f519d24c77fb63455ca6c92680"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "ad901b4be50941ac3bb74cba2242fde263cb7d2aa4fd690edf4d4ad2719f9cfe"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "2179f68ef6654f66b965a685a5b9297aa68ccd67"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "1c1d3a4f7fbb1124b234da1070b124f051ca7d98ebcb1a0ca14048f7f0659a41"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "cd79e3d2b48bd05bfa0622db276e868a5f5cfe90"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "28f56c1fdbf99017952978f11102bd626af11f8322899386b00f37c085f70434"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "e95c94cf1af60007763d607d9ec38668a91764e5"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "10dc6acbc09b67ffde8497e9528bcd9e105e206a5925395d028bf41850c4a2f5"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "beccedccb2095fa0f408675b5cf9b10b6cd897d7"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "2d53068831c160a0f775dd2334cd060aacdac4a2d2b9cec85b7bdd7e3a6c5bb4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+1/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
