[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "692cfe331dfcfb7e28dc4d9ecbbf70207e7a69c1"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "693b4ab63b6f21e8ed91a169005d3cf01433d80f161a3d73c9e57997f50ef36c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "db05beff2f5c278b8917535979568c469d5e8c2d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "192f243717b39994f67a662e7249a9743876da918b7b11f9fe6313ab548e15b5"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "e7c286af5e0e2b09676f00fcf4e5cf2ce9f4797e"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e38438283268187402deb5dcd9dcf27f26fcb1f1b2239aa81f3bb2fbbcceeccc"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "c7e72c481657bf831119ffff51eea89144e404b5"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "057bbc1748206500a418d745416bac854859ab37c87ae07ca408d089d6ea1e27"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "dda098e9a899bbc6cb285e17b3c386faffc39d32"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "59da92e27578ed630c32c36f25ba423f50873d2195e9b976e8e1e31fda8126d2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "d016a3664f6f90d597d3e7635b0c513b8c2a5ce5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "620a3b944c039a57f50559ebfe2fdc96e3e60fd9b9bf773c9d33e0e75b35e86f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "9346ba5dddf6ddeb44da5328c2c65a89a6a6bb7d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ee2db4e596148e5f10f81575bb7eb37e013635a5d68bd054e43692f0fdf7e7fe"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1df3e47bb57067a93bd9dc0532875a0e45c92700"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "366dfb9c94dfa4f175b9fd89682311537f366444589f321cb7f07454c6c2d26a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "32f0c3fae36bf4e6089b57675ac8b0aed56654b1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ee89bb3d9cf717e83a652ebfaa44b92d5049af8e0428527bb3b9a35c246d5044"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7221984b5a19dd978f76498058262bfdae919fe8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "fc9eb0f7480842b971fbd53e3194f3788ffd0e898986080ce9c520b573101fad"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5ff31200ae29d8025427a6de62bd946ce0fe44ea"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "4510b2719bd38d74650b3ef7820c4a2e6535d632bb5419a1a70a5f31df9e8b3c"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "af7dbf95ec4467ccbfc9dbd3e9adf160ae9a8798"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "59168322fc925bbd4ccfaa30cc4f22494f5c08b23e56e92c5ef6e76df7a31d72"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "1ef445d0f7b23eeeec7e99082c14450b9af9425b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "328c40f6c240fceafbcb3da8180d74cf138d7188d38f724ee508937889e17bf3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "03910ae9beb520ee163ce690610cbd177c079aac"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "102f69afccd6fd97520b09e4774edac6fca2785770261950e556c76e88d28594"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "96bd5f23e91c9e1efe08e4ad032af8d631dcaf9b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "cdadfb15148411213e4f0bb7d282e3a5789e8434a9d742326de5b9978f77fbc4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9efaa45969fa467057e68f2bd0cb9e22c4bee4ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "868c3d9122600d8b5dfe39036064566d52001c30609dc063c957e016b8f39bbb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8eb3ab2127544fa27a5c66266a4a04524774148"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1aa26689d6682a7b284331080d97cfaec24ac6b52097c6ceaa3c6ef43ea81e16"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "641b5f36ad491c90e0d919a93997ba2a89ce9110"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f73718cd1059463a13cfa5487225da030b76b897b6fd55815c29b4648a99d5a9"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "9dfd8ad0e69b748d7e44cd0139dd2c563ac25524"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "98848f8d5b61d328464ae11d465504e9b7a12daf8b7e00cad0498cab301fbfc5"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "9bca4d7d24034e8de9d05c643da05d405fca4224"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c13471976c1d261782ef15f52ab717007eded349e8b9cdaeeec61494854d1586"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "9dfa8c54be27c3afe310078914c30c3a89087049"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ca3e205ea92519bb62ceeb88e990098df519d49bb7169f70d0276ec780b29629"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "00bf969914aa9be6f675accc941b52aef76eba07"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8b9395023ecb1fc5b1c72ac60022a46aa1ab14a4fc261c411a5246b42f79ff15"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "8c65bb5abd787ddae5043784d4ecd56b01ec45bc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "07b748c346561915cd677c5452dec339d28372948aca0eed65702819e5f7db0a"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "4403329e8962189aa0ec7a3a6bb866d3d3073229"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "a1092b320148627fcf8ddb7f4196077d788a33088431f26cb1487937b6549f3e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "6b71db31d376e69f17fe6e7736f71ee009fb825d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "52e43ee132e69e2d9b01e1809772180509bf822ee123b2eb4ae48d2997411ffe"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "0140aa0f1a527b14800f7ed51651b16488f2795a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c6a0c3177277e11e733dc391b4dd219d893b5f132085c0a46e779e36273593a7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "63fa97f506d28837fe40a8af0d1f59634355ed88"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "916f5cc98a4e3bfe0f24aeda3066ca901bcd0210408d101455686147dbf918d4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "e5e72cf7054f6e926af0595f91283424711f6b5e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "79e6dd21bb544d57fa926c857ebf171816ec1d575ff5e84ae7253eaad017c84f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "485330c9e5bca1cbe1116ae6d80f0700ce563d46"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "85bd7a57ab8ddee8fa2e7efddb881b5a6a37741e33177263704d237ad9abccb3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "dc6173ff3694a2a9143393b2f5f6f0a7ce2cdf53"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "481efedd428053b1ee27383698bcc0f2a04178febf1557f389d39e8e28940eb8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "218dbe72503c04efe6a221f5b527a70f99bde050"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "8b0657d81712cf914073d4d3ae01d9fdbeba3e3d8d9ad0663b110168fac38b3d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "d22196243b8448c24854068182cde8b44740ce01"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "185b463a49a692aa0574dd8d5f2ed6177456c66ccb09f694533a550fb7fc8a11"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "81e3efa3b8cc1b632b567bd953f14f2b697c7013"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c77ed1e12e11ec370ff38fdf771a3c9a89d9c9b79309a084426845484aff5802"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c5f54a32b38902d192cc667808c45799ee3d7fec"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "8c4ab90e20127f9ef517412da853cfa4695c3795072c20fc26302bee0cb2371d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "6cb9f5b5af9e5304733e4955d25b2e98dc870dcc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d99a2ed68a5ff080c339b49d31c9e1c91776198c1fa44813c824303c4f82aaf0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "9a9245abd976e65c47c8f4ae80141401e0b475dc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "27b7982ee42b7c184263c0491a83b77f0bb6e4167a7a1e5fbdf8c53b86701011"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "b8f899faf106cb4a06caeac6366c1970433c856c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "75082cf1de98df8f10c833062844bed33bb02640aebc7e0b443c83a80c90140f"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "236c2d4fe76f0dde96095416c54fd5bc6951c2af"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "170e1a7228186de3470cc7153ead8a7983918ac982e478ebaaca4661c5e002cf"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "741fcd975d5c25ceddfe8c19b2cab812e3f95373"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "8225c9f9cf036cc126047e277fb0cf47674d64bdcf7bbecc644e2b9f22c71bbb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c811a91436b910b664d9f962958f5fe19634f9e0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "8cbda6e118d0b6fd08bc62e4e4b66a81f3910166be8494f77b1a004fe813feeb"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "82403c98f193cd430e08eae0298155a2ca6054c3"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "e4f9261321a398d02c36d7c256940ae8a1f2d91694a3d8878911b10e7ce242d1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "99a284babdd1362e528d542d702ee3e45cedf432"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "b6e6eb99acba5814845d482bb52e7019a4af6bedb4441ec7df9648b06ad26312"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "b0021810ce994eb4c6217fe07392d7823dfd43e9"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "0890ac03c2455321dd526eaf6de3760e7460e2e5a6720f42eb0c74683bb61d62"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+3/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
