[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "edd2e638ae4b16ae39468918b1183e8dfd187733"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "5c824dbb4593cae9a174322dd4bfec0ab27313a038f68f36ca6f9b06bb21cab2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "8ed71e02e4fbd71ca7518f578ea755a510b3f662"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "38bab9a32656a546b442c99ac89f1bc05f231e55db86500d2f0118d4a2020748"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "420f10cf1cbda567c2b1566fe098079a1b772221"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b7192900bff9d87ebea429274532af5ac04e3519898d7f57634bf4e12cf1e0ea"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "4f6d9580174fba70f42e296c10a4902a0fb7d5df"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "bf5684d0ec38db58423e38f6adab13f0b43e7ab313a689a2610e98d211eaa021"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "6e4d788f5dc686afccc980bf7bc87790f789ba49"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "76c46b59b50e6d8e9ee275a4678887a7e9ace17003a3da966dbf67487711cc3d"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "e829537335a07b0d5e0d10f00d401011c77331ae"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "43515c9517ac2b6cfe69d7f7d20cf6e5013caba5d514619037c42ae5d0fb8706"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "aarch64"
git-tree-sha1 = "306e649ff8908a34050948b9c601793cb867247d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ed8aac33e629d67bcbd2d3f9d2231ecffbd44d0b750f5aac7b440c74b756f477"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "edea3852e3e9361f0463b83e22d20927bd9a18be"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "06ca5b2b2a8ba2bc62f7e028ba34c47d7e5b904d6d273a6003b3a65b539a7257"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "278f1260aebc2be2a49d0507cb343cb5381cadec"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e304dcd2959360d170e3b0fa61754aa71600e1331758dafd97c1e53e997e9d45"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "08f79989af66ebbce6387a686618a8013e56dcb3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d54493400fcdd0347887470b87285894536d6c268bac29d64e688f89a88bee60"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "f95191c514753d15cde5dd85467053d3575c4ea1"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "cfd280d2a6d1a41417b8b674fc14d06b82799e2247facd100160c8f630d06f17"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b68c28702724bc2003c3f777dbe5dc221391c841"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "99f91c0d2bc728f104cde8ce13ef9270bf9b0ab8a678022743143c1b0e85e7fc"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b292ab1524ed4a53278e4e7c20a546440cd30213"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "4b870fc1352fa7e822c41fd11078511aa93170545637e56b4f17aba7629cca92"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "56e1a98e40b351dfe75162e5fe8d54afa3896290"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "e59c82a730ec740ba7b7b1656b75ab38c13c3b6ec74373f20f41c071de5c2f84"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6399f5f6d1d239eed7d7a5a21d68721e28655161"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "7a5e9d089b89771af8be3e2153a10d43115da56f24668c5779fa7efdebd33bb7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "36c86d9d5c12a3c8c93dfb0e1c28978735358e38"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "9c410b924024723d4d3105ddb67b1cff38901f862ecfdad1c94709fe28e4d9e0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b90da01830720cb9dc06d76e81341f3f385786e0"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "1780f5f9c0060d2fdebdf6f6d6972f9b591b57c83b782f45161751cf6fe53535"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "167b4a010c0d70ee82e7b5cfa8c2b0e6c2e51ed3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "5eb73bce616d20e66416ca39a2b390fc46a3d482379bd55f423aecaba8fcd8ba"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[PETSc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1d7023038be1576aa877d1185f34de3c008093cc"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "b972235c4f3b1096e64cb8bd8530837f5b3bbe074b5cf4f92988171f3afcb3da"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "790f23841f6183767308fb7110527851a431d22f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "d68da506d9fc7ceba0cdac890bab78f62a904a9bb1fa8e0ca819ea47cad796a0"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "789ca033e728880b9746e0f0eb8a19e864d7ba5b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ea20aaa4baa757922994b789270e53fe03a91423f8039c2474fd5d1b4d66424b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "8029c74630c7555a4c4e1f8c94dd3e10e406693e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "105d205d750821132b791e8e69c0db722c37598ebee65850034d7050a88d41c8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "74787fb6936630e2b4b5c4dd742305b8b1247d3f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "58924d5793e289d8c0a76332e763ec810ee0e69cc8d726b67041a7cc35a053ae"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "8305e9cec0757087e5e766f7c082e11708708845"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c1ec4858f2863149a6446cb0954607774af4cf442ce29e1fb0f0fdbc59a5b9d4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "i686"
git-tree-sha1 = "f68e4723bffe09abe92f543468d4d626b1e84b24"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "77c5602b7d50f7697031013d445f09381b00ffb19be0949dbc3f5349e2becf73"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.i686-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "9ab7252db2b2cbbf5b50477bcd10393e75e39786"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "de404985fb8b713e31ce36d8240ea669d26b0a89c3e951c9a398a46bac84d02b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "1a6c660418d918fa48f659b568592fe07cac32d5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c83a80fc0a9f3ed7166d0eddd784c06d8d63d60f84929cb259e98c4ca9d96999"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "powerpc64le"
git-tree-sha1 = "9d9a04c7d1cdf176adfa91d658af38a87c67efd2"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "59eb30b73abe59a0fe83381424e5a60633ac636530ef0851926698d2a0399d71"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "a4d4dc045270b8923a07f55cab6656fef7888755"
libgfortran_version = "3.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "3cbed0dc127d94806a25a4ec0cff0cac62eb0f68851dbe85795672d1231d4ab1"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7f81d36210419fcbad2214633436e25d2a811469"
libgfortran_version = "4.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "4fb43823a9a6b40d3f8f1bb825ca8f578883aaa11e13d55248f0903b4c7d5ee4"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "ec515847449bdf6fb8c898bdd5986dc93186c912"
libgfortran_version = "5.0.0"
os = "macos"

    [[PETSc.download]]
    sha256 = "13fcefa142456c91503fd935cf0cbfc9796fa9470821fffe536597431c925c90"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7ee0e8dcc4934cda16141a493ad3d493a62fdd23"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "f5f8a33259d7955980e98043362f4873f0055901693e12a2990e057ed24656c8"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "fa9460c3975c69aeccc10b79a16cf6e0a41d4678"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "fa458a3d317fbf3633747dcdbc35ac3f09230cae85874b7ff10f73bb702952c2"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "724ebba0bbcd1420e32b088b628eaa6d7b68e1f3"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "c30bbb1f709935705838698a3061cc4d1e189c991bcb16e0fd785c0366438387"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "12ba7db9e9db4e41d52dc100b36b186a5c6c4e69"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "dc8f7f2e49b5b23ba5fbc6b5b48a7f9925e2d260b179f72c500c92a41be3556e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "3bae83acdef97e97885dc9cf496300c7207bc314"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "ecff2a89a811a5e330c50f08d8c391569c1f29a8631899845d6f38d3a935f72e"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7c4f78ed2d2e9b642e5469345d720c6e8e2f6e78"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[PETSc.download]]
    sha256 = "824ab898094e04804980c72cc48252d0033b4925becc916552ec178119ba30b3"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "8b36d1596fa4db3a52750e4047187d51c3a12207"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "4798050fc09f5463f9aaa613d44aa798143735ed0c7d7926d43334d4ec34ead6"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "7219a4c01afc79a5b18b18eb7b334b8882fec7cb"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "1f4ff3ad96c5317aaff71feffc3b5525a26c79f7e2a5b9e45808ab4dad48a974"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "9b1d5bd7322dd6ab9fe9ca3cc3fe31525e8aa048"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[PETSc.download]]
    sha256 = "97610d65b82a3b8deb406ebf3e3fa80bc259df83a42966cf1c2a25c5b19d4a85"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "557457ad557fd930cb6d9348bba2c46f80dfe16f"
libgfortran_version = "3.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "0e461113e06f6d5a2fe14cb968a82e8e7bd785e27d6333b9d7ad74f6af8897f7"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "c4a7409e99dd18050a391ffb371e38e82287678a"
libgfortran_version = "4.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "06b0a54406403bbe923eda80eec2178128a7188f80c5f6304765a12b87300361"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[PETSc]]
arch = "x86_64"
git-tree-sha1 = "07bd2b9204a513e590d6e8b7f2cab8e01f2bef0f"
libgfortran_version = "5.0.0"
os = "windows"

    [[PETSc.download]]
    sha256 = "f22340b2da60f3e3b6d83a6ea72b6ef9ec99355321442a2c37e32b1d2c116d8b"
    url = "https://github.com/JuliaBinaryWrappers/PETSc_jll.jl/releases/download/PETSc-v3.16.5+4/PETSc.v3.16.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
